---
pre-commit:
  parallel: true
  commands:
    actionlint:
      glob: '*.{yml}'
      root: .github/workflows
      run: actionlint {staged_files}
    spellcheck:
      run: just spellcheck
    detect-secrets:
      run: gitleaks detect --log-opts="$(git merge-base origin/main HEAD)..HEAD" --no-banner --redact --verbose
    frontend-lint:
      glob: '*.{js,ts,vue}'
      root: ui
      run: just frontend lint --fix {staged_files}
      stage_fixed: true
    backend-lint:
      glob: '*.{py}'
      root: src
      run: just backend lint
    format-just:
      glob:
        - '*.just'
        - '.justfile'
      stage_fixed: true
      run: |
        for file in {staged_files}; do
          just --justfile "$file" --fmt --unstable
        done
