packages: []

catalogs:
  build:
    '@intlify/unplugin-vue-i18n': 11.0.3
    '@shikijs/markdown-it': 3.20.0
    '@unocss/eslint-config': 66.5.10
    '@vitejs/plugin-basic-ssl': 2.1.0
    '@vitejs/plugin-vue': 6.0.3
    beasties: 0.3.5
    markdown-it-link-attributes: 4.0.1
    rollup: 4.54.0
    shiki: 3.20.0
    unocss: 66.5.10
    unplugin: 2.3.11
    unplugin-auto-import: 20.3.0
    unplugin-vue-components: 30.0.0
    unplugin-vue-macros: 2.14.5
    unplugin-vue-markdown: 29.2.0
    unplugin-vue-router: 0.15.0
    vite: 7.3.0
    vite-bundle-visualizer: 1.2.1
    vite-plugin-inspect: 11.3.3
    vite-plugin-pwa: 1.2.0
    vite-plugin-vue-devtools: 8.0.5
    vite-plugin-vue-layouts: 0.11.0
    vite-ssg: 28.2.2
    vite-ssg-sitemap: 0.10.0
  dev:
    '@iconify-json/carbon': 1.2.15
    '@iconify-json/mdi': 1.2.3
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/vue': 8.1.0
    '@vitest/eslint-plugin': 1.5.4
    '@vue-macros/volar': 3.1.1
    '@vue/eslint-config-prettier': 10.2.0
    '@vue/eslint-config-typescript': 14.6.0
    '@vue/test-utils': 2.4.6
    cypress: 15.8.1
    cypress-vite: 1.8.0
    eslint: 9.39.2
    eslint-plugin-cypress: 5.2.0
    eslint-plugin-format: 1.1.0
    eslint-plugin-playwright: 2.4.0
    eslint-plugin-testing-library: 7.15.1
    https-localhost: 4.7.1
    openapi-typescript: 7.10.1
    taze: 19.9.2
    typescript: 5.9.3
    vitest: 4.0.16
    vue-tsc: 3.1.8
  frontend:
    '@unhead/vue': 2.0.19
    '@unocss/reset': 66.5.10
    '@vueuse/core': 14.1.0
    nprogress: 0.2.0
    openapi-fetch: 0.15.0
    pinia: 3.0.4
    vue: 3.5.26
    vue-i18n: 11.2.2
    vue-router: 4.6.4
  types:
    '@types/markdown-it-link-attributes': 3.0.5
    '@types/nprogress': 0.2.3

onlyBuiltDependencies:
  - esbuild
  - cypress
