/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Checkbox: typeof import('./components/ui/checkbox/Checkbox.vue')['default']
    Field: typeof import('./components/ui/field/Field.vue')['default']
    FieldContent: typeof import('./components/ui/field/FieldContent.vue')['default']
    FieldDescription: typeof import('./components/ui/field/FieldDescription.vue')['default']
    FieldError: typeof import('./components/ui/field/FieldError.vue')['default']
    FieldGroup: typeof import('./components/ui/field/FieldGroup.vue')['default']
    FieldLabel: typeof import('./components/ui/field/FieldLabel.vue')['default']
    FieldLegend: typeof import('./components/ui/field/FieldLegend.vue')['default']
    FieldSeparator: typeof import('./components/ui/field/FieldSeparator.vue')['default']
    FieldSet: typeof import('./components/ui/field/FieldSet.vue')['default']
    FieldTitle: typeof import('./components/ui/field/FieldTitle.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Item: typeof import('./components/ui/item/Item.vue')['default']
    ItemActions: typeof import('./components/ui/item/ItemActions.vue')['default']
    ItemContent: typeof import('./components/ui/item/ItemContent.vue')['default']
    ItemDescription: typeof import('./components/ui/item/ItemDescription.vue')['default']
    ItemFooter: typeof import('./components/ui/item/ItemFooter.vue')['default']
    ItemGroup: typeof import('./components/ui/item/ItemGroup.vue')['default']
    ItemHeader: typeof import('./components/ui/item/ItemHeader.vue')['default']
    ItemMedia: typeof import('./components/ui/item/ItemMedia.vue')['default']
    ItemSeparator: typeof import('./components/ui/item/ItemSeparator.vue')['default']
    ItemTitle: typeof import('./components/ui/item/ItemTitle.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    README: typeof import('./components/README.md')['default']
    RobotForm: typeof import('./components/RobotForm.vue')['default']
    RobotItem: typeof import('./components/RobotItem.vue')['default']
    RobotList: typeof import('./components/RobotList.vue')['default']
    RobotProfile: typeof import('./components/RobotProfile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Textarea: typeof import('./components/ui/textarea/Textarea.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
