// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
  baseUrl: 'http://localhost:8000' | (string & {})
}

/**
 * HTTPValidationError
 */
export interface HttpValidationError {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * Robot
 */
export interface Robot {
  /**
   * Name
   */
  name: string
  /**
   * Is Great
   */
  is_great?: boolean
}

/**
 * ValidationError
 */
export interface ValidationError {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export interface RobotListData {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/robot/'
}

export interface RobotListResponses {
  /**
   * Response Robot List
   * Successful Response
   */
  200: Array<Robot>
}

export type RobotListResponse = RobotListResponses[keyof RobotListResponses];

export interface RobotCreateData {
  body: Robot
  path?: never
  query?: never
  url: '/api/v1/robot/'
}

export interface RobotCreateErrors {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RobotCreateError = RobotCreateErrors[keyof RobotCreateErrors];

export interface RobotCreateResponses {
  /**
   * Successful Response
   */
  201: Robot
}

export type RobotCreateResponse =
  RobotCreateResponses[keyof RobotCreateResponses];

export interface UtilitiesHealthData {
  body?: never
  path?: never
  query?: never
  url: '/api/health'
}

export interface UtilitiesHealthResponses {
  /**
   * Successful Response
   */
  200: unknown
}
