packages: []

catalogs:
  build:
    '@intlify/unplugin-vue-i18n': 11.0.3
    '@shikijs/markdown-it': 3.22.0
    '@unocss/eslint-config': 66.6.0
    '@vitejs/plugin-basic-ssl': 2.1.4
    '@vitejs/plugin-vue': 6.0.4
    beasties: 0.4.1
    markdown-it-link-attributes: 4.0.1
    rollup: 4.57.1
    shiki: 3.22.0
    unocss: 66.6.0
    unplugin: 3.0.0
    unplugin-auto-import: 21.0.0
    unplugin-vue-components: 31.0.0
    unplugin-vue-macros: 2.14.5
    unplugin-vue-markdown: 29.2.0
    unplugin-vue-router: 0.19.2
    vite: 7.3.1
    vite-bundle-visualizer: 1.2.1
    vite-plugin-inspect: 11.3.3
    vite-plugin-pwa: 1.2.0
    vite-plugin-vue-devtools: 8.0.6
    vite-plugin-vue-layouts: 0.11.0
    vite-ssg: 28.3.0
    vite-ssg-sitemap: 0.10.0
  dev:
    '@iconify-json/carbon': 1.2.18
    '@iconify-json/mdi': 1.2.3
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/vue': 8.1.0
    '@vitest/eslint-plugin': 1.6.9
    '@vue-macros/volar': 3.1.2
    '@vue/eslint-config-prettier': 10.2.0
    '@vue/eslint-config-typescript': 14.6.0
    '@vue/test-utils': 2.4.6
    cypress: 15.10.0
    cypress-vite: 1.8.0
    eslint: 9.39.2
    eslint-plugin-cypress: 5.3.0
    eslint-plugin-format: 1.4.0
    eslint-plugin-playwright: 2.5.1
    eslint-plugin-testing-library: 7.15.4
    https-localhost: 4.7.1
    openapi-typescript: 7.13.0
    taze: 19.9.2
    typescript: 5.9.3
    vitest: 4.0.18
    vue-tsc: 3.2.4
  frontend:
    '@unhead/vue': 2.1.4
    '@unocss/reset': 66.6.0
    '@vueuse/core': 14.2.1
    nprogress: 0.2.0
    openapi-fetch: 0.17.0
    pinia: 3.0.4
    vue: 3.5.28
    vue-i18n: 11.2.8
    vue-router: 5.0.2
  types:
    '@types/markdown-it-link-attributes': 3.0.5
    '@types/nprogress': 0.2.3

onlyBuiltDependencies:
  - esbuild
  - cypress
