name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

env:
  UV_CACHE_DIR: /tmp/.uv-cache
  CI: true
  REGISTRY: "ghcr.io"
  IMAGE_BACKEND: "lambchop4prez/fmv-demo-backend"
  IMAGE_FRONTEND: "lambchop4prez/fmv-demo-frontend"
  OIDC_AUDIENCE: ${{ secrets.OIDC_AUDIENCE }}
  OIDC_ISSUER: ${{ secrets.OIDC_ISSUER }}
  OIDC_SIGNING_KEY_ID: ${{ secrets.OIDC_SIGNING_KEY_ID }}
  SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Analyze | Run static code analysis
        run: just analyze

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Test | Run all unit tests
        run: just unit-test
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Force correct release branch on workflow sha
        run: git checkout -B ${{ github.ref_name }}

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Setup | Setup docker compose
        uses: docker/setup-compose-action@e29e0ecd235838be5f2e823f8f512a72dc55f662

      - name: Continuous Integration
        env:
          GITHUB_TOKEN: ${{github.token}}
        id: ci
        run: just ci

      - name: Collect artifacts
        if: ${{ steps.ci.outputs.released != 'false' }}
        env:
          NEW_RELEASE: ${{ steps.ci.outputs.released }}
          NEW_VERSION: ${{ steps.ci.outputs.version }}
        run: just artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: artifacts
          path: artifacts/

    outputs:
      new-release-detected: ${{ steps.ci.outputs.released }}
      new-release-version: ${{ steps.ci.outputs.version }}
      new-release-tag: ${{ steps.ci.outputs.tag }}
      new-release-is-prerelease: ${{ steps.ci.outputs.is_prerelease }}

  test-e2e:
    name: End-to-End Testing
    runs-on: ubuntu-latest
    needs: [analyze, test, ci]
    if: needs.ci.outputs.new-release-detected !='false'
    permissions:
      contents: read
      artifact-metadata: read
    env:
      NEW_VERSION: ${{ needs.ci.outputs.new-release-version }}
      TAG: ${{ needs.ci.outputs.new-release-version }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Setup | Setup docker compose
        uses: docker/setup-compose-action@e29e0ecd235838be5f2e823f8f512a72dc55f662

      - name: Setup | Download artifacts
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
        with:
          name: artifacts
          path: artifacts/

      - name: Setup | Load artifacts
        run: just load

      - name: Setup | Bring environment up
        run: just up

      - name: Run E2E tests
        run: just e2e
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: test-artifacts
          if-no-files-found: ignore
          path: |
            ui/test/logs/

      - name: Teardown | Bring environment down
        if: always()
        run: just down

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ci, test-e2e]
    if: github.event_name != 'pull_request' && (needs.ci.outputs.new-release-detected !='false')
    permissions:
      contents: write
      artifact-metadata: write
      attestations: write
      id-token: write
      packages: write
      issues: write
    env:
      NEW_VERSION: ${{ needs.ci.outputs.new-release-version }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref_name }}

      - name: Setup | Force release branch to be at workflow sha
        run: |
          git reset --hard ${{ github.sha }}

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Setup | Login to GitHub Container Registry
        uses: docker/login-action@292fe2d7ee5389e283d2c71e565819146798c2e2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Download artifacts
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
        with:
          name: artifacts
          path: artifacts/

      - name: Setup | Load artifacts
        run: just load

      - name: Release | Attest artifact provenance
        uses: actions/attest@c65e8d47370080bc2ce65b721b2fb5044a21718d
        with:
          subject-path: 'artifacts/**.tar.gz'
      
      - name: Release | Create release
        env:
          GITHUB_TOKEN: ${{github.token}}
        run: just release
      
      - name: Release | Publish release
        env:
          GITHUB_TOKEN: ${{github.token}}
        run: just publish
      
      - name: Release | Get image digests
        id: digest
        run: |
          echo "frontend=$(just digest-frontend)" >> "$GITHUB_OUTPUT"
          echo "backend=$(just digest-backend)" >> "$GITHUB_OUTPUT"
      
      - name: Release | Attest frontend image provenance
        uses: actions/attest@c65e8d47370080bc2ce65b721b2fb5044a21718d
        with:
          subject-name: ${{ env.REGISTRY }}/${{env.IMAGE_FRONTEND}}
          subject-digest: ${{ steps.digest.outputs.frontend }}
          push-to-registry: true
      
      - name: Release | Attest backend image provenance
        uses: actions/attest@c65e8d47370080bc2ce65b721b2fb5044a21718d
        with:
          subject-name: ${{ env.REGISTRY }}/${{env.IMAGE_BACKEND}}
          subject-digest: ${{ steps.digest.outputs.backend }}
          push-to-registry: true
      