name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

env:
  UV_CACHE_DIR: /tmp/.uv-cache
  CI: true

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Analyze | Run static code analysis
        run: just analyze

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Test | Run all unit tests
        run: just unit-test
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Force correct release branch on workflow sha
        run: git checkout -B ${{ github.ref_name }}

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Setup | Setup docker compose
        uses: docker/setup-compose-action@8cccb8c14b6500aaffebff1aa49c502c34d2e5e6

      - name: Continuous Integration
        id: ci
        run: just ci

      - name: Collect artifacts
        env:
          NEW_VERSION: ${{ steps.ci.outputs.version }}
        run: just artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: artifacts
          path: artifacts/

    outputs:
      new-release-detected: ${{ steps.ci.outputs.released }}
      new-release-version: ${{ steps.ci.outputs.version }}
      new-release-tag: ${{ steps.ci.outputs.tag }}
      new-release-is-prerelease: ${{ steps.ci.outputs.is_prerelease }}

  test-e2e:
    name: End-to-End Testing
    runs-on: ubuntu-latest
    needs: [analyze, test, ci]
    permissions:
      contents: read
      artifact-metadata: read
    env:
      NEW_VERSION: ${{ needs.ci.outputs.new-release-version }}
      TAG: ${{ needs.ci.outputs.new-release-version }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Setup environment
        uses: ./.github/actions/setup

      - name: Setup | Setup docker compose
        uses: docker/setup-compose-action@8cccb8c14b6500aaffebff1aa49c502c34d2e5e6

      - name: Setup | Download artifacts
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3
        with:
          name: artifacts
          path: artifacts/

      - name: Setup | Load artifacts
        run: just load

      - name: Setup | Bring environment up
        run: just up

      - name: Run E2E tests
        run: just frontend e2e
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: test-artifacts
          if-no-files-found: ignore
          path: |
            ui/test/logs/

      - name: Extract logs
        if: always()
        run: just e2e-logs

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: test-logs
          if-no-files-found: ignore
          path: |
            artifacts/e2e/

      - name: Teardown | Bring environment down
        if: always()
        run: just down
